# Generated by Django 4.1 on 2023-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_room_schedule_room_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='schedule',
            field=models.JSONField(default={'oioi': 'ajshdjsd'}),
        ),
    ]
