# Generated by Django 4.1 on 2023-01-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_room_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='schedule',
            field=models.JSONField(default={'25/1/2023': []}),
        ),
    ]
