# Generated by Django 4.1 on 2023-01-25 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_room_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='expected_time',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='schedule',
        ),
        migrations.AddField(
            model_name='procedure',
            name='day',
            field=models.DateField(default=datetime.datetime.now, help_text='Dia da cirurgia', verbose_name='Day of the event'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='end_time',
            field=models.TimeField(default='07:00', help_text='Horário final', verbose_name='Final time'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(default='', help_text='Nome do procedimento', max_length=200),
        ),
        migrations.AddField(
            model_name='procedure',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='Horário de início', verbose_name='Starting time'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='surgery_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
