# Generated by Django 4.1 on 2023-01-25 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_procedure_date_remove_procedure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data da cirurgia'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='end_time',
            field=models.TimeField(default='07:00', verbose_name='Horário de final (esperado)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome do procedimento'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='start_time',
            field=models.TimeField(default='07:00', verbose_name='Horário de início'),
        ),
    ]
