# Generated by Django 4.1 on 2023-01-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_procedure_day_alter_procedure_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='surgery_room',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
