# Generated by Django 4.1 on 2023-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_procedure_surgery_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='surgery_room',
        ),
        migrations.AddField(
            model_name='procedure',
            name='surgery_room',
            field=models.ManyToManyField(default='', to='api.room'),
        ),
    ]
