# Generated by Django 4.1 on 2023-01-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_procedure_surgery_room_procedure_surgery_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='surgery_room',
        ),
        migrations.AddField(
            model_name='procedure',
            name='surgery_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
