# Generated by Django 4.1 on 2023-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_room_procedure_procedure_surgery_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['surgery_room']},
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Terminado'),
        ),
    ]
